classdef animalList
    
    properties
        
        mouseList = {'vg15';  ...
                     'vg16';  ...
                     'vg17';  ...
                     'vg18';  ...
                     'vg20';  ...
                     'vg22';  ...
                     'vg23' };
        
    end
    
    properties (Constant)
        
        gridList  = {'veryReducedGridBilateral_v3.mat';     ...
                     'veryReducedGridBilateral_v3.mat';     ...
                     'fullGridBilateral.mat';               ...
                     'fullGridBilateral.mat';               ...
                     'fullGridBilateral.mat';               ...
                     'fullGridBilateral.mat';               ...
                     'fullGridBilateral.mat'                ...
                     };
                   
        powerList = {6; ...
                     6; ...
                     6; ...
                     6; ...
                     6; ...
                     6; ...
                     6};
        
        varPower  = [false;     ...
                     false;     ...
                     true;      ...
                     true;      ...
                     true;      ...
                     true;      ...
                     true];
                   
        epochList = {'3epochs'; ...
                     '3epochs'; ...
                     'whole';   ...
                     'whole';   ...
                     'whole';   ...
                     'whole';   ...
                     'whole'};
                   
        runOnLsr  = [true;      ...
                     true;      ...
                     true;      ...
                     true;      ...
                     false;     ...
                     true;      ...
                     true];

    end
    
    methods
        
        function obj = addToList(obj,mouse)
            obj.mouseList{end+1} = mouse{1};
            obj.mouseList{end+1} = 'add new';
        end
    end
end